### PR TITLE
Project Structure 

### PR DESCRIPTION
**Pull request by JuanGalvez12**

### CODE REVIEW

**Comment by moselGlez** [comment]
prueba review

**Comment by irvingesp2190** [comment]
Is missing the following folders:
src/controllers
* admin.controller.js
* at-sce.controller.js

Public:
* css
* img
* js

src/routes
* admin.routes.js
* at-sce.routes.js

src/services
* at-sce-api.service.js

Views:
* layouts/main.hbs
* partials
    - errors.hbs
    - footer.hbs
    - messages.hbs
    - errors.hbs
    - navigation.hbs
* calculator.hbs
* signin.hbs

Please do the chages.

**Comment by moselGlez** [comment]
Excelente

**Review by AT-ivillamil — CHANGES_REQUESTED** [review]
src/controllers/ar-stc.controller.js is not the right name, it should be `at-sce.controller.js`

**Review by irvingesp2190 — APPROVED** [review]

**Review by moselGlez — APPROVED** [review]

**Review by AT-ivillamil — COMMENTED** [review]
The objects containing the functions in the controllers must be declared before assigning them the functions. e.g. `const adminCtrl = {}`. This should be on top of the file.

**Review by Emiliano-Plascencia — APPROVED** [review]

**Review by AT-ivillamil — APPROVED** [review]

**Pull request merged**
